---
apiVersion: cpet.belastingdienst.nl/v1alpha2
kind: Paas
metadata:
  name: example-paas
spec:
  quota:
    limits.memory: 32Gi
    requests.cpu: "8"
    requests.memory: 16Gi
    requests.storage: 50Gi
  capabilities:
    argocd:
      custom_fields:
        git_url: "https://github.com/my-org/my-demo-paas.git"
        git_revision: main
        git_path: .
    grafana: {}
    sso: {}
  groups:
    admins:
      query: "CN=my-demo-admins,OU=Groups,DC=example,DC=com"
      roles:
        - admin
    developers:
      users:
        - benoit.schipper@hcs-company.com
        - jan.kappert@hcs-company.com
        - wander.boessenkool@hcs-company.com
      roles:
        - edit
    viewers:
      users:
        - stakeholder
      roles:
        - view
  namespaces:
    dev:
      groups:
        - admins
        - developers
    prod:
      groups:
        - admins
    tekton:
      groups:
        - admins
        - developers