---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paas-grafana
  namespace: openshift-gitops
spec:
  generators: []
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ .paas }}-capability-grafana'
    spec:
      destination:
        namespace: '{{ .paas }}-grafana'
        server: 'https://kubernetes.default.svc'
      project: paas
      source:
        chart: capability-grafana
        repoURL: ghcr.io/inholland-cloud-minor-2526/paas-capabilities
        targetRevision: 0.1.2
        helm:
          valuesObject:
            namespace: '{{ .paas }}-grafana'
            paas: '{{ .paas }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
