---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paas-sso
  namespace: openshift-gitops
spec:
  generators: []
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ .paas }}-capability-sso'
    spec:
      destination:
        namespace: '{{ .paas }}-sso'
        server: 'https://kubernetes.default.svc'
      project: paas
      source:
        chart: capability-sso
        repoURL: ghcr.io/benoitschipper/paas-demo
        targetRevision: 0.1.0
        helm:
          valuesObject:
            namespace: '{{ .paas }}-sso'
            paas: '{{ .paas }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
