---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - appset_paas-argocd.yaml
  - appset_paas-grafana.yaml
  - appset_paas-sso.yaml
  - rb_paas-applicationset-manager.yaml