---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opr-paas
  name: selfsigned-issuer
  namespace: paas-system
spec:
  selfSigned: {}
