---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: paas-argocd
  namespace: platform-argocd
  annotations:
    argocd.argoproj.io/sync-options: ApplyOutOfSyncOnly=true
spec:
  generators: []
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{ .paas }}-capability-argocd'
    spec:
      destination:
        namespace: '{{ .paas }}-argocd'
        server: 'https://kubernetes.default.svc'
      project: paas
      source:
        chart: capability-argocd
        repoURL: ghcr.io/inholland-cloud-minor-2526/paas-capabilities
        targetRevision: 0.1.3
        helm:
          valuesObject:
            namespace: '{{ .paas }}-argocd'
            groups: '{{ .groups }}'
            paas: '{{ .paas }}'
            git_url: '{{ .git_url }}'
            git_path: '{{ .git_path }}'
            git_revision: '{{ .git_revision }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
