---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - generate-allow-from-cnpg-operator.yaml
  - generate-allow-from-openshift-ingress.yaml
  - generate-allow-from-openshift-monitoring.yaml
  - generate-allow-same-namespace.yaml
